services:
  postgres:
    image: postgres:15-alpine
    container_name: orderdb
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    command: >
      postgres
      -c max_connections=400
      -c shared_buffers=512MB
      -c effective_cache_size=2GB
      -c maintenance_work_mem=128MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=32MB
      -c default_statistics_target=100
      -c work_mem=8MB
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d orderdb"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
